services:
  db:
    image: postgres
    container_name: Baza_de_date
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: website
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python runserver.py"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - nginx
  nginx:
    image: nginx:latest
    container_name: NGINX
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - .\nginx_wsgi:/etc/nginx
      - .\nginx.conf:/etc/nginx/nginx.conf
      - .\assets:/etc/nginx/static
      - .\mime.types:/etc/nginx/mime.types