# Generated by Django 3.2.4 on 2022-03-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numele', models.CharField(max_length=60)),
                ('prenumele', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=60)),
                ('mesajul', models.CharField(max_length=300)),
            ],
        ),
    ]
